dist: bionic
language: python

jobs:
  include:
  - stage: test
    env: PYTHON3
    python: 3.6
    install:
     - pip -q install -U flake8
    script:
     - flake8 ./python/
  - stage: test
    env: POSTGRES
    addons:
      postgresql: 10
      apt:
        packages:
        - postgresql-10-postgis-2.4
    
    before_script:
     - echo "\set ON_ERROR_STOP on" > ~/.psqlrc
    script:
     - cd sql; sed -e 's/@DB_USER@/postgres/' db_settings.sh.template > db_settings.sh; POSTGRES_USER=postgres ./create-db.sh
     - psql -U postgres hazard < common.sql
     - psql -U postgres hazard < hazard-schema.sql
